baseURL = "https://sportinsightreport.com/"
languageCode = "en-gb"
title = "Sport Insight Report"
theme = "ananke"
robots = "index, follow"

[menu]

  [[menu.main]]
    identifier = "home"
    name       = "Home"
    url        = "/"
    weight     = 1

  [[menu.main]]
    identifier = "reports"
    name       = "Reports"
    url        = "/reports/"
    weight     = 2

